### ISSUE TITLE
Img load glitch

### ISSUE THREAD

**Issue by jdtsmith** [cubiq/SwipeView#2]
Wonderful tool and fast moving development.  I am basing (updating, rather) a [Zenphoto](http://zenphoto.org) theme for iPhone on this.  I'm still on v0.3, but this comment should apply to the new version as well. 

I'm loading largish images which use almost every pixel of the retina display, and find that the current method of removing the "swipeview-loading" class as soon as the page is "flipped" and the IMG src is updated results in frequent glitches where the old image is still visible for a fraction of a second (often abnormally stretched since the dimensions may have changed), before the new one is downloaded and displayed.  The solution I found was to have the masterPage class cleared _only after_ image load.  This is complicated by the generality of your newer versions (since it knows nothing of the content being paged through).  I solved it by removing your class-clearing code, and adding my own, following the SwipeView creation:

```
var images=document.getElementsByTagName("img");
for(var i=0;i<images.length;i++) {
  images[i].onload=function () {
    this.parentNode.className='';
  }
}
```

In the new v0.10, it looks like removing the class-clearing code from `__flip` and letting the user `onflip` callback handle clearing the swipeview-loading class after image load would work similarly.  Since the page might contain multiple images, etc., I can't think of how to let swipeview do this itself and maintain the current generality.  One idea to make this more straightforward would be to create public "setActive" and "setLoading" codes that the user can use in their custom callbacks.  If a user flip event handler exists, it would be responsible for calling setActive after it updates the page contents.  If not, your __flip handler does this itself.

**Comment by cubiq** [comment]
thanks for your insightful report. as you noted I'm trying to keep swipeview as more general purpose as possible. Initially I wanted to integrate all the functionalities inside the core script, but I like the current setup where the user can hook to custom events to build any kind of app.

In your scenario I'd add a custom "loading" class to the image onflip and remove it on image load. I'll modify the example accordingly.

**Comment by cubiq** [comment]
should be fixed, better yet would be to completely override the default swipeview-loading style, but it should work anyway
