### ISSUE TITLE
No stop function

### ISSUE THREAD

**Issue by chrisafennell** [cubiq/SwipeView#24]
I've setup SwipeView to autoplay using SetInterval and next() function. Once autoplay starts... I can't figure out what function to use to stop the autoplay. I tried creating a new function with this.directionX = 0 and this.x = 0 but that doesn't seem to work correctly. It makes the swipe reverse instead of stopping it. Any ideas or advice would be greatly appreciated.

**Comment by cubiq** [comment]
Use clearInterval. Eg:

var timer = setInterval(..., 2000);
...
clearInterval(timer);

**Comment by chrisafennell** [comment]
Thanks a million Matteo. Incredible script!

**Comment by ghost** [comment]
@chrisafennell i would be love to know how to move automatically through images! can you share your script please?

**Comment by ghost** [comment]
<code>setInterval(function(){
    gallery.next();
},2000)</code>

**Comment by chrisafennell** [comment]
Thats exactly what I use.

**Comment by ghost** [comment]
and to stop it? (im a js noob plus i cant decide what event should stop
it.. navigating? if touching could pause it, that would be sick!

**Comment by chrisafennell** [comment]
This is the code I'm currently using. What it does is autoplay the SwipeView if the mouse hasn't moved for a certain length of time. Hope this helps.

var timer = null;
var prevX = 0;
var prevY = 0;
var flip = null;

slidernext = function() {
  slider.next();
}

timeoutTrigger = function() {
  // Autoplay Slider
  flip = setInterval(function() { slidernext(); }, 7500);

}

compareCoords = function(coord, value) {  
  return coord != value;
}

$(window).mousemove(function(event) {
  x = compareCoords(prevX,event.clientX);
  y = compareCoords(prevY,event.clientY);
  if (!x && !y) {
    return;
  }
  prevX = event.clientX;
  prevY = event.clientY;
  clearInterval(flip);
  clearInterval(fullAds);
  clearTimeout(timer);
  timer = setTimeout( function() {
    timeoutTrigger();
  }, 30000 );
});
