### ISSUE TITLE
Glitch with content wrapped inside links.

### ISSUE THREAD

**Issue by chrisafennell** [cubiq/SwipeView#25]
I'll try to explain this the best I can.

Currently some of the content in my SwipeView slider is wrapped in "< a >" tags. This causes SwipeView to not complete its flip whenever I am swiping through the content that is wrapped in "< a >" tags. I have to click again and release to get SwipeView to finish the flip. Any ideas on how to prevent this?

**Comment by cubiq** [comment]
don't use A tags, use a custom tap event instead. This is your the best option.

**Comment by chrisafennell** [comment]
So try a normal tag with a "click" action binded to it?

**Comment by cubiq** [comment]
Custom tap event (touchstart + touchend). Something like this https://github.com/alexgibson/tap.js

**Comment by chrisafennell** [comment]
Oh I see. I'll look into that, but this application is running on windows machines and not mobile. Hopefully in the future it'll be moved to Android.

**Comment by cubiq** [comment]
you may try with a standard click event, then
