### ISSUE TITLE
Problem with onload="setTimeout(function() { window.scrollTo(0, 1) }, 100);"

### ISSUE THREAD

**Issue by ghost** [cubiq/SwipeView#9]
Any solution to hide the url bar on load?

**Comment by cubiq** [comment]
what is the problem? it doesn't seem swipeview related.

**Comment by ktch** [comment]
Sorry Matteo. Usually I just use <body onload="setTimeout(function() { window.scrollTo(0, 1) }, 100);"> to hide the browser chrome when someone visits the page, for more UI space on mobile, but there appears to be something in SwipeView that is preventing this from firing.

**Comment by ktch** [comment]
Hid my code:

```
<body onload="setTimeout(function() { window.scrollTo(0, 1) }, 100);">
```

**Comment by cubiq** [comment]
probably your document doesn't have enough screen height to hide the url bar. Try to add a 100px padding-bottom to the body

**Comment by ktch** [comment]
Of course... Works fine, though I had to add the padding to the top to prevent a gap at the bottom.

You're the man, thank you. Do you know of a way to create a "handle" on the page if the user does want to return to the URL bar in this case? Without going inline? I may have to eventually go inline anyway, but I'm trying to see what my options are.

Thank you for creating SwipeView. It's by far the smoothest, butteriest implementation I've seen.
